name: Docker Image DEVENV

on:
  push:
    paths:
      - 'test/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v3
        name: Checkout
      -
        name: ls -la
        run: ls -la
